
(define a (v) (+ 1 2 v))
(println "(a 4)=" (a 4))
(define b () (+ 1 2))
(println "(b)=" (b))

(define c (lambda (v) (+ 1 2 v)))
(println "(c 4)=" (c 4))
(define d (lambda () (+ 1 2)))
(println "(d)=" (d))


(define counter 0)
(define (inc1)
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  ))
(inc1)
(println "Counter1:" counter)
(define counter 0)
(define (inc2)(begin
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  )))
(inc2)
#|
(println "Counter2:" counter)
(define counter 0)
(define inc3 (lambda ()
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  )()))
(inc3)
(println "Counter3:" counter)
(define counter 0)
(define inc4 (lambda ()(begin
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  ))()))
(inc4)
(println "Counter4:" counter)

(define counter 0)
(define inc5 (lambda ()
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  )))
(inc5)
(println "Counter5:" counter)
(define counter 0)
(define inc6 (lambda ()(begin
  (dotimes (i 1000)
    (set! counter (+ counter 1))
  ))))
(inc6)
(println "Counter6:" counter)
|#
